### ISSUE TITLE
siac_output.json not created by SIAC

### ISSUE THREAD

**Issue by SFrav** [MarcYin/S2_TOA_TO_LAI#1]
Using the current master I get an error towards the end of the TOA2LAI_S2 function. After atmospheric correction, it tries to read a file called `siac_output.json` in the S2 image folder (line 72 in TOA2LAI_S2::AC_LAI). However, this file isn't created by SIAC V2.3.5. 

What am I missing? Lines 72-19 of TOA2LAI_S2 assume that `siac_output.json` is created in the S2 image folder after running `SIAC_S2`. Right?

Details: Windows 10, Python 3.6. Installed in virtual env as follows
```
pip install -U pylibjpeg-openjpeg
pip install numpy==1.19.3 #error with 1.19.4
pip install GDAL-3.1.4-cp36-cp36m-win_amd64.whl #Download gdal whl https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal
pip install https://github.com/MarcYin/S2_TOA_TO_LAI/archive/master.zip
```

**Comment by MarcYin** [comment]
Hi, this is developed with my local version of SIAC, which has not been pushed to remote and has a function to create a summery json for the SIAC process. This has been added to the latest release: be82ff331682b6c04a52cbf78a439a3a0800bd74.

**Comment by SFrav** [comment]
Great. Thanks for the prompt update, Mark!

I failed at a few attempts to reverse engineer the json file. I'll be curious to see how the paths are structured in there.

**Comment by MarcYin** [comment]
Cheers, it should work now, but I have not tested it, so issues are welcome.

**Comment by SFrav** [comment]
Glad to confirm - it's working well. I had to generalise for cross-platform compatibility, but these were minor changes overall.

**Comment by MarcYin** [comment]
Hi, there was an error in the azimuth angles scaling, and it has been updated in the latest push a0c784f38847fc91188a16866a3aa9af25d568b8. If you are still using it, it is recommended to update the LAI retrieval.

**Comment by SFrav** [comment]
Thanks. Updated. I’ll test by the end of the week.

**Comment by SFrav** [comment]
Hi, with the scaling corrections we’re getting much better predictions compared to ground truth values.

**Comment by MarcYin** [comment]
Hi, good to know that. It would be interesting to see what you are using it for and we are doing works related to crop monitoring over different places as well.
